version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
